//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMono.UI.Launch
{
    public partial class LaunchForm
    {
        public const string URL = "ui://0jo9lqvcn3k40";

        #region [子节点]
 
        private FairyGUI.GButton m_BtnTest;
   
        #endregion

        #region [控制器]

        #endregion

        #region [动效]

        #endregion
        
        private void RegisterComponents()
        {
            #region [子节点]
 
            m_BtnTest = (FairyGUI.GButton)ContentPane.GetChild("btnTest");
   
            #endregion

            #region [控制器]

            #endregion

            #region [动效]

            #endregion
        }
    }
}