//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLogic.UI.Login
{
    public partial class LoginForm
    {
        public const string URL = "ui://6apezyp2hjkq0";

        #region [子节点]
 
        private GameLogic.UI.Login.LoginComp m_LoginComp;
 
        #endregion

        #region [控制器]

        #endregion

        #region [动效]

        #endregion
        
        private void RegisterComponents()
        {
            #region [子节点]
 
            m_LoginComp = (GameLogic.UI.Login.LoginComp)ContentPane.GetChild("loginComp");
 
            #endregion

            #region [控制器]

            #endregion

            #region [动效]

            #endregion
        }
    }
}